language: "node_js"
install:
    - npm install -g serverless
    - npm install
script:
    - npm test
deploy:
  skip_cleanup: true
  provider: script
  script: sls deploy
  on:
    all_branches: true
node_js:
    - "node"
