language: "node_js"
deploy:
  provider: lambda
  function_name: "restApi-production-api"
  region: "ap-southeast-1"
  role: "arn:aws:iam::060486774331:role/restApi-production-ap-southeast-1-lambdaRole"
  runtime: "nodejs10.x"
  handler_name: "lambda.handler"
  on:
    all_branches: true
node_js:
    - "node"
