language: "node_js"
deploy:
  provider: lambda
  function_name: "restApi-production-api"
  region: "ap-southeast-1"
  role: "arn:aws:lambda:ap-southeast-1:060486774331:function:restApi-production-api"
  runtime: "nodejs4.3"
  handler_name: "handler"
  on:
    all_branches: true
node_js:
    - "node"
