service: restApi #Name of your App

provider:
 name: aws
 runtime: nodejs10.x # Node JS version
 memorySize: 512
 timeout: 15
 stage: production
 region: ap-southeast-1 # AWS region

package:
  exclude:
    - 'tests/**'
    - 'tests-integration/**'
    - '.idea/**'
    - 'serverless-configs/**'
    - 'envs/**'
    - 'support/**'
    - 'node_modules/.cache/**'
    - 'scripts/**'
    - 'frontend/**'

functions:
 api:
   handler: index.handler
   events:
     - http: ANY {proxy+}
     - http: ANY /
